#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 14 10:07:44 2023

@author: mhurtgen
"""

import streamlit as st
import getcomposers as gc

df=gc.getcomposerperiodinstrument('0','all','0')#(p,i,t)
st.title('Prolific composers')